Repository Coordipai/web-server, pull requests merged in 2025-06, with the labels that each got.

#185 fix: Handle project with no files
  src/project/service.py
Labels: 🐞 BugFix

#184 chore: Fix api path for bot
  src/bot/router.py
Labels: 🔨 Refactor

#188 hotfix: Add bot router to get all issues for user
  src/bot/router.py
  src/project/repository.py
Labels: 🐞 BugFix

#189 hotfix: Fix issue rescheduling request duplicate issue
  src/issue_rescheduling/repository.py
Labels: 🐞 BugFix

#198 refactor: Move unregister function to user from auth
  src/auth/router.py
  src/auth/service.py
  src/user/router.py
  src/user/service.py
Labels: 🔨 Refactor

#197 refactor: Refactor project api
  src/project/repository.py
  src/project/router.py
  src/project/schemas.py
  src/project/service.py
  src/response/error_definitions.py
  src/user/repository.py
Labels: 🔨 Refactor

#199 feat: Add requester info and issue title in IssueReschedulingRes
  src/common/util/permissions.py
  src/config/middleware.py
  src/issue_rescheduling/models.py
  src/issue_rescheduling/schemas.py
  src/issue_rescheduling/service.py
  src/response/error_definitions.py
Labels: ✨ Feature

#202 fix: Change find_projects_by_member parameter in bot
  src/bot/router.py
Labels: 🐞 BugFix

#203 feat: Add permission checker for get_project
  src/common/util/permissions.py
  src/project/service.py
  src/response/error_definitions.py
Labels: ✨ Feature

#206 fix: Add exception if project or user not found
  src/bot/router.py
Labels: 🐞 BugFix

#210 hotfix: Make serializable json object (project, issue) when communicating with llm
  src/agent/tool.py
Labels: 🐞 BugFix

#212 hotfix: Amend wrong typo in FeedbackRes
  src/agent/schemas.py
Labels: 🐞 BugFix

#213 fix: Add function to update project name
  src/common/util/permissions.py
  src/project/repository.py
  src/project/service.py
Labels: 🐞 BugFix

#215 fix: Fix middleware to verify user existence before allowing API requ…
  src/config/middleware.py
Labels: 🐞 BugFix

#217 fix: Handle streaming response error in generate_issues endpoint
  src/agent/router.py
Labels: 🐞 BugFix

#218 hotfix: Amend type of assignees at RecommendAssigneeRes
  src/agent/schemas.py
Labels: 🐞 BugFix

#219 hotfix: Amend type of issue title at RecommendAssigneeRes
  src/agent/schemas.py
Labels: 🐞 BugFix
