Repository Coordipai/web-server, pull requests merged in 2025-05, with the labels that each got.

#37 fix: Include GitHub username when redirecting after GitHub OAuth login
  src/auth/service.py
Labels: ✨ Feature

#40 feat: Implement issue crud functions
  src/issue/__init__.py
  src/issue/repository.py
  src/issue/router.py
  src/issue/schemas.py
  src/issue/service.py
  src/main.py
  src/response/error_definitions.py
  src/response/success_definitions.py
  src/user/schemas.py
Labels: ✨ Feature

#44 feat: Return user profile img in UserRes object
  src/auth/service.py
  src/user/models.py
  src/user/schemas.py
  src/user/service.py
Labels: ✨ Feature

#53 feat: Add UserRes to issue assignee list
  src/issue/repository.py
  src/issue/schemas.py
  src/user/models.py
  src/user/repository.py
Labels: ✨ Feature

#55 feat: Add member profile img in ProjectUserRes object
  src/project/schemas.py
Labels: ✨ Feature

#57 build: Remove copy env file script
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#64 feat: Add function to get all issues from repository
  src/issue/repository.py
  src/issue/router.py
  src/issue/schemas.py
  src/issue/service.py
Labels: ✨ Feature

#65 feat: Implement CRUD for issue rescheduling requests
  src/issue_rescheduling/__init__.py
  src/issue_rescheduling/models.py
  src/issue_rescheduling/repository.py
  src/issue_rescheduling/router.py
  src/issue_rescheduling/schemas.py
  src/issue_rescheduling/service.py
  src/models/__init__.py
  src/project/models.py
  src/response/error_definitions.py
  src/response/success_definitions.py
Labels: ✨ Feature

#67 feat: Change field size of career
  src/user/models.py
Labels: ✨ Feature

#71 feat: Sort imports and remove unused imports automatically
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
  src/agent/chain.py
  src/agent/prompts.py
  src/agent/router.py
  src/agent/schemas.py
  src/agent/tool.py
  src/auth/router.py
  src/auth/service.py
  src/auth/util/github.py
  src/auth/util/jwt.py
  src/auth/util/redis.py
  src/config/config.py
  src/config/database.py
  src/config/logger_config.py
  src/config/middleware.py
  src/issue/repository.py
  src/issue/router.py
  src/issue/schemas.py
  src/issue_rescheduling/models.py
  src/issue_rescheduling/repository.py
  src/issue_rescheduling/router.py
  src/issue_rescheduling/schemas.py
  src/main.py
  src/models/__init__.py
  src/project/models.py
  src/project/repository.py
  src/project/router.py
  src/project/schemas.py
  src/project/service.py
  src/project_user/models.py
  src/project_user/repository.py
  src/response/handler.py
  src/response/schemas.py
  src/response/success_definitions.py
  src/user/models.py
  src/user/repository.py
  src/user/router.py
  src/user/schemas.py
  src/user/service.py
  src/user_repository/models.py
  src/user_repository/repository.py
  src/user_repository/router.py
  src/user_repository/service.py
Labels: ✨ Feature

#77 feat: Add api for returning summary of issue states in project
  src/issue/repository.py
  src/issue/router.py
  src/issue/schemas.py
  src/issue/service.py
  src/response/error_definitions.py
Labels: ✨ Feature

#76 feat: Add api for getting all projects
  src/project/repository.py
  src/project/router.py
  src/project/schemas.py
  src/project/service.py
  src/project_user/repository.py
Labels: ✨ Feature

#78 feat: Change repo_fullname to project_id in issue CUD
  src/issue/repository.py
  src/issue/router.py
  src/issue/schemas.py
  src/issue/service.py
Labels: ✨ Feature

#81 hotfix: Change cookie secure setting when redirect after GitHub login
  src/auth/service.py
Labels: 🐞 BugFix

#87 build: Remove redundant workflow and add restart workflow
  .github/workflows/deploy.yml
  .github/workflows/restart.yml
Labels: 🌏 Deploy

#88 fix: Change discord_id field type to string
  src/auth/schemas.py
  src/project/models.py
  src/project/router.py
  src/project/schemas.py
  src/project/service.py
  src/user/models.py
  src/user/schemas.py
Labels: 🐞 BugFix

#90 fix: Set cookie options conditionally based on local or produnction e…
  src/auth/service.py
  src/config/config.py
Labels: ✨ Feature

#92 chore: Change restart workflow name to Restart
  .github/workflows/restart.yml
Labels: 🌏 Deploy

#94 hotfix: Update middleware to fix CORS
  src/config/middleware.py
  src/main.py
Labels: 🐞 BugFix

#95 hotfix: Fix redirection issue in routers
  src/agent/router.py
  src/issue/router.py
  src/issue_rescheduling/router.py
  src/project/router.py
  src/user_repository/router.py
Labels: 🐞 BugFix

#99 feat: Add request method and path info in ErrorResponse
  src/config/middleware.py
  src/response/handler.py
  src/response/schemas.py
Labels: ✨ Feature

#101 hotfix: Fix missing parmeter when update user response
  src/auth/service.py
  src/response/success_definitions.py
Labels: 🐞 BugFix

#102 hotfix: Add allow path for refreshtoken in middleware
  src/config/middleware.py
Labels: 🐞 BugFix

#103 hotfix: Implement update user
  src/auth/router.py
  src/auth/service.py
Labels: 🐞 BugFix

#104 hotfix: Implement updating existing user
  src/auth/service.py
  src/user/service.py
Labels: 🐞 BugFix

#105 hotfix: Fix TypeError in project_id IN clause by wrapping with list
  src/issue_rescheduling/repository.py
Labels: 🐞 BugFix

#113 hotfix: Remove await when create project
  src/project/router.py
Labels: 🐞 BugFix

#115 feat: Refactor error handling system with unified structure and enhanced detail messages
  src/auth/util/jwt.py
  src/config/config.py
  src/config/database.py
  src/config/middleware.py
  src/config/trace_config.py
  src/issue/repository.py
  src/issue_rescheduling/repository.py
  src/project/repository.py
  src/project/router.py
  src/project_user/repository.py
  src/response/error_definitions.py
  src/response/handler.py
  src/response/report_error.py
  src/response/schemas.py
  src/stat/service.py
  src/user/repository.py
  src/user_repository/repository.py
Labels: ✨ Feature, 🔨 Refactor

#116 hotfix: Fix Typo in middleware exception
  src/config/middleware.py
Labels: 🐞 BugFix

#119 hotfix: Fix middleware ErrorResponse missing parameters
  src/config/middleware.py
  src/response/handler.py
  src/response/schemas.py
Labels: 🐞 BugFix

#126 hotfix: Add file paths to function parameters that generate ProjectRe…
  src/project/service.py
Labels: 🐞 BugFix

#127 build: Refactor docker compose update script
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#128 hotfix: Generate issues with streaming service
  src/agent/chain.py
  src/agent/router.py
  src/agent/tool.py
Labels: 🐞 BugFix

#132 fix: Add issue rescheduling deletion type
  src/issue_rescheduling/router.py
  src/issue_rescheduling/service.py
  src/response/error_definitions.py
Labels: ✨ Feature

#133 feat: Get feedback for rescheduling issue from gemini
  src/agent/chain.py
  src/agent/prompts.py
  src/agent/router.py
  src/agent/schemas.py
  src/agent/tool.py
  src/response/error_definitions.py
  src/response/success_definitions.py
Labels: ✨ Feature

#137 hotfix: Fix logic for updating project member
  src/project/schemas.py
  src/project/service.py
Labels: 🐞 BugFix

#136 hotfix: Exclude user names when request for assigning issues
  src/agent/chain.py
  src/agent/prompts.py
  src/agent/router.py
  src/agent/schemas.py
  src/agent/tool.py
Labels: 🐞 BugFix

#142 hotfix: Remove all files in design_docs not directory itself
  src/config/volume_config.py
Labels: 🐞 BugFix

#145 hotfix: Amend parameter
  src/agent/chain.py
Labels: 🐞 BugFix

#144 feat: Add sprint number to issue info
  src/agent/chain.py
  src/agent/prompts.py
  src/agent/schemas.py
  src/agent/tool.py
Labels: ✨ Feature

#147 hotfix: Add lines for checking invalid repsonse
  src/agent/chain.py
  src/agent/prompts.py
  src/agent/tool.py
  src/auth/service.py
Labels: 🐞 BugFix

#146 chore: Define method to generate schemas from other object
  src/agent/chain.py
  src/agent/schemas.py
Labels: 🧹 CleanUp

#148 hotfix: Rename document paths and add parameter
  src/agent/chain.py
  src/project/service.py
Labels: 🐞 BugFix

#149 hotfix: Check project name duplicated when updating project
  src/project/service.py
Labels: 🐞 BugFix

#151 hotfix: Add missed field
  src/agent/schemas.py
Labels: 🐞 BugFix

#150 chore: Drop database only in local environment
  src/main.py
Labels: ✨ Feature

#152 hotfix: Fix logic for updating project name
  src/project/service.py
Labels: 🐞 BugFix

#157 hotfix: Change missing token error to 401
  src/response/error_definitions.py
Labels: 🐞 BugFix

#158 hotfix: Drop design-docs only in local environment
  src/main.py
Labels: 🐞 BugFix

#162 chore: Amend prompts for assigning issues
  src/agent/chain.py
  src/agent/prompts.py
  src/user/repository.py
Labels: ✅ Test

#168 feat: Amend prompt to generate more than 10 issues
  src/agent/prompts.py
Labels: 🔨 Refactor

#169 fix: Check project_user before unregister
  src/auth/service.py
  src/response/error_definitions.py
  src/user_repository/repository.py
Labels: 🐞 BugFix

#171 feat: Update issue according to IssueReschedulingRequest
  src/issue_rescheduling/repository.py
  src/issue_rescheduling/router.py
  src/issue_rescheduling/schemas.py
  src/issue_rescheduling/service.py
  src/response/success_definitions.py
Labels: ✨ Feature

#172 feat: Check user category is valid when registering or updating user
  src/user/schemas.py
Labels: ✨ Feature

#173 build: Enable Docker layer caching using GitHub Actions cache
  .github/workflows/deploy.yml
Labels: 🔨 Refactor, 🌏 Deploy

#175 feat: Update GitHub accessToken when login
  src/auth/service.py
  src/user/service.py
Labels: ✨ Feature

#180 hotfix: Connect bot router to app
  src/main.py
Labels: ✨ Feature
